### ISSUE TITLE
Netty issues when connecting replicas

### ISSUE THREAD

**Issue by goncalotomas** [bft-smart/library#26]
I followed the Getting Started with BFT-SMaRt wiki page and implemented my own version of `DefaultRecoverable`. Everything compiles without an issue - but running server replicas results in seeing a rather long stack trace. As far as I know I'm following instructions correctly, but I can't be certain.

I tried using the latest version by cloning the repository and using the .jar files from master, but still no luck. Here's what happens:

Replica 0 boots and operates correctly.
Replica 1 boots and reports connection with 0 was successful.
When I start Replica 2, only `#Using view stored on disk` is seen on the output, and Replica 1 outputs:

```java
Session Created, active clients=0
io.netty.handler.codec.DecoderException: java.lang.NegativeArraySizeException
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:299)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NegativeArraySizeException
	at bftsmart.communication.client.netty.NettyTOMMessageDecoder.decode(NettyTOMMessageDecoder.java:121)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:268)
	... 12 more
```

**Comment by goncalotomas** [comment]
To whom it may concern, this issue appears to exist after changing the hosts.config file.
By leaving the hosts.config file unaltered I can avoid this issue completely. I didn't understand what caused this to happen though.

**Comment by snakejerusalem** [comment]
Are you launching the clients before all replicas are all running and ready? Judging from the output you show, it seems like it is what you are doing. If this is indeed the case, try to launch all replicas and wait for them to be ready before starting the clients. Notice that a replica is ready when each one outputs "(DeliveryThread.run) canDeliver released.".

**Comment by snakejerusalem** [comment]
Also, if you are changing the hosts.config file, don't forget to delete the file 'config/currentView'. If such file exists, the library will fetch the hosts from that file instead of the configuration hosts.config.

**Comment by goncalotomas** [comment]
No, I was launching server replicas before any clients were started. The crash happens when the 3rd replica tries to connect to the 2 already running replicas.
I was deleting the currentView file between runs just to be safe, but that was not the issue. There seems to be some hidden dependency on the current form of hosts.config. If I leave it unchanged, it works. If I modify it in any way (making sensible changes and mimicking the original format) I get that error.

**Comment by snakejerusalem** [comment]
Please, provide us the content of your host.config file with which this issue happens.

**Comment by goncalotomas** [comment]
Aside from the comments, the file only contains:

#server id, address and port (the ids from 0 to n-1 are the service replicas) 
0 127.0.0.1 10000
1 127.0.0.1 10001
2 127.0.0.1 10002
3 127.0.0.1 10003

**Comment by andreneonet** [comment]
When you run all server replicas in the same machine (127.0.0.1), you cannot set the port numbers that way (10000,10001,10002,10003). Each replica binds the port number (to receive messages from clients) and the next port number (to receive message from the other replicas). 

For instance, server replica 0 binds the following ports: 10000 and 10001. This way server replica 1 will not be able to bind the port number 10001.

Please, try this host.config file configuration:
#server id, address and port (the ids from 0 to n-1 are the service replicas)
0 127.0.0.1 10000
1 127.0.0.1 10002
2 127.0.0.1 10004
3 127.0.0.1 10006

**Comment by goncalotomas** [comment]
OK. I didn't know that. That would be nice to include in the documentation though.
I just tested it and it runs just fine. I would not have guessed that the replicas used 2 different ports.

Thank you @andreneonet for clearing up the mistery! :+1:

**Comment by snakejerusalem** [comment]
@goncalotomas , you are right. We have now included this constrain in the readme file.

**Comment by snakejerusalem** [comment]
Here are a few guidelines to have in mind while deploying the library (new wiki page): https://github.com/bft-smart/library/wiki/Deployment-Guidelines
