### ISSUE TITLE
ServiceProxy.invoke hangs if only one nodes is running

### ISSUE THREAD

**Issue by Kangmo** [bft-smart/library#29]
# Problem 
When no nodes are connected, but only one node is running, the second call to ServiceProxy.invoke hangs

## Reproduction Step 
1. Start only one node. 
2. call ServiceProxy.invok twice with different data.
3. second call hangs.

## Root cause 
When there an exception is raised, the canSend lock is not unlocked.

```
exception : java.lang.RuntimeException: Server not connected, message : Server not connected, occurred at : java.lang.RuntimeException: Server not connected
	at bftsmart.communication.client.netty.NettyClientServerCommunicationSystemClientSide.send(NettyClientServerCommunicationSystemClientSide.java:383)
	at bftsmart.tom.TOMSender.TOMulticast(TOMSender.java:150)
	at bftsmart.tom.ServiceProxy.invoke(ServiceProxy.java:197)
	at bftsmart.tom.ServiceProxy.invokeOrdered(ServiceProxy.java:143)

```

## Solution
We need to unlock the canSend lock in the ServiceProxy.invoke method in the finally clause.

**Comment by Kangmo** [comment]
Could you check if your code has similar issue in other methods as well?
Attached is the example.

If you think you can accept my pull request fixing this issue, I will send one. 
Please let me know how to run the unit tests, because unit tests in my machine fail.
(So that I can make sure I did not break any thing tested by unit test cases)
[a.txt](https://github.com/bft-smart/library/files/658630/a.txt)
