### ISSUE TITLE
Can't run example counter

### ISSUE THREAD

**Issue by Raycoms** [bft-smart/library#80]
I was trying to run the example counter project. But got the following error:

`javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.Handshaker.activate(Handshaker.java:509)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1474)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1346)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at bftsmart.communication.server.ServerConnection.ssltlsCreateConnection(ServerConnection.java:571)
	at bftsmart.communication.server.ServerConnection.<init>(ServerConnection.java:119)
	at bftsmart.communication.server.ServersCommunicationLayer.getConnection(ServersCommunicationLayer.java:246)
	at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:193)
	at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:65)
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:148)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:140)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:90)
	at bftsmart.demo.counter.CounterServer.<init>(CounterServer.java:45)
	at bftsmart.demo.counter.CounterServer.main(CounterServer.java:85)
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:931)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:71)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at bftsmart.communication.server.ServersCommunicationLayer.run(ServersCommunicationLayer.java:333)
`

In general I was interested in how many consensus rounds per second BFT-Smart runs.
It's 80k ops per second when the ops are 0. But how many ops do you process per consensus round?

So, is there a rough estimate at rounds per second?

**Comment by evsward** [comment]
I met the same issue.

**Comment by ted-git66** [comment]
I had the same trouble. In the config/system.config file try to uncomment the line 196:
`# With cipher (recommended).`
`system.ssltls.enabled_ciphers = TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
` 

It solved for me and I was able to run the example. I hope it will solve for you as well.

Best regards and good luck
